### ISSUE TITLE
clustercode-admin no command specified

### ISSUE THREAD

**Issue by evoicefire** [ccremer/clustercode#12]
Hi,
This may be an easy fix but I can't seem to work it out. When I try and run the example docker compose file (with docker up) I get the error: 
`ERROR: for clustercode-admin  Cannot create container for service clustercode-admin: No command specified
ERROR: Encountered errors while bringing up the project.
`
This is my docker-compose.yml:

[docker-compose.txt](https://github.com/ccremer/clustercode/files/2890171/docker-compose.txt)

What am I missing?
Thanks in advance!

**Comment by ccremer** [comment]
Sorry for not getting back earlier to you.
There are two issues:
1. The `latest` tag isn't stable anymore. Use the specific version tag
2. You copied the config for the 2.x branch, which isn't released yet. But 1.3 is the latest release. Here's your updated compose file:
```yaml
version: "2.2"
services:
  # The backend
  clustercode:
    restart: unless-stopped
    image: braindoctor/clustercode:1.3.2
    container_name: clustercode
    cpu_shares: 512
    ports:
      - "7600:7600/tcp"
      - "8080:8080"
    volumes:
      - "/root/clustercode/input:/input"
      - "/root/clustercode/output:/output"
      - "/root/clustercode/profiles:/profiles"
# If you need modifications to the xml files, persist them:
#      - "/path/to/config:/usr/src/clustercode/config"
    environment:
    # overwrite any settings from the default using env vars!
      - CC_CLUSTER_JGROUPS_EXT_ADDR=192.168.200.85
```
just a sidenote: you may need to specify `CC_CLUSTER_JGROUPS_TCP_INITIAL_HOSTS` when in cluster mode.
The wrong copy is my fault, I will update the readme shortly.
Please test it again :)
